rm o2simtopology_12984.json
rm o2sim_configuration.ini
rm MCStepLoggerVolMap.dat
rm o2sim_proc-cut.dat
rm o2sim_geometry.root
rm o2sim_12993.root
rm o2sim_12993_par.root
rm MCStepLoggerSenVol.dat
rm gphysi.dat
rm o2sim_workerlog0
rm o2sim_serverlog
rm o2sim_mergerlog
rm o2sim_Kine.root
rm o2sim_HitsITS.root
rm sim.log
rm o2simdigitizerworkflow_configuration.ini
rm tpc_polya.root
rm collisioncontext.root
rm o2sim_grp.root
rm itsdigits.root
rm dig.log
rm o2itsrecoflow_configuration.ini
rm rec.log
rm o2trac_its.root
rm o2clus_its.root
rm dpl-config.json
